name: Verify

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          reporter: github-pr-check
          fail_on_error: true
          filter_mode: nofilter
          fail_level: any
  verify-abi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: gradle/actions/setup-gradle@v4
      - name: Check ABI
        run: ./gradlew checkAbi

  verify-android-jvm-wasm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew detekt

      - name: Test compiler plugin
        run: ./gradlew tiamat-destinations-compiler:test

      - name: Build Android target
        run: ./gradlew sample:composeApp:assembleDebug

      - name: Build Jvm target
        run: ./gradlew sample:composeApp:packageDistributionForCurrentOS

      - name: Build Web target
        run: ./gradlew sample:composeApp:wasmJsBrowserDistribution

  verify-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: 17

      - name: Set up Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 16.4.0

      - name: Build iOS App
        run: xcodebuild -project sample/iosApp/iosApp.xcodeproj -scheme iosApp -configuration Debug -sdk iphonesimulator build
